### ISSUE TITLE
UI problem

### ISSUE THREAD

**Issue by RafalKolin** [IIS-ZPI/ZPI2019_zaoczni_PIECIU_zamiast_300-stu#38]
![bug1](https://user-images.githubusercontent.com/29921738/74891032-14541800-5386-11ea-87ac-cead3875b7c8.png)
![bug2](https://user-images.githubusercontent.com/29921738/74891036-161ddb80-5386-11ea-9c4b-44d0b0740d7e.png)
After recently changes, I have a problem with UI in application. The layout is completely crash.

**Comment by piotrl3w** [comment]
#40 FIXED
![Screenshot_20200220-102953](https://user-images.githubusercontent.com/48412332/74920732-ed6d0480-53cc-11ea-820a-2602c915fd64.jpg)
![Screenshot_20200220-102958](https://user-images.githubusercontent.com/48412332/74920736-ee9e3180-53cc-11ea-9a40-efeeecf94b18.jpg)
